### ISSUE TITLE
Fix: Team view doesn't let you fix one Pokémon if another Pokémon is causing a problem.

### ISSUE THREAD

**Issue by FlorianKutz** [DeveloperKhan/pogo-web#101]
See this video. The messages from the server are as expected.
https://user-images.githubusercontent.com/18531173/113588937-08cabb80-9631-11eb-9a9f-5fbcc933321e.mp4

**Comment by DeveloperKhan** [comment]
Fixed, I just removed team validation until you try to save the entire team (not just a single Pokemon)
