### ISSUE TITLE
Feat: Charge Move Buttons

### ISSUE THREAD

**Issue by DeveloperKhan** [DeveloperKhan/pogo-web#11]
Implement Pokemon GO style charge move UI.

### Requirements

- [x] There should be one or two charge move button components on the `/pages/game` screen
- [x] Each component should have a label and a circular button
- [x] There should be a background element that fills up based on the current Pokemon's energy and the energy of the corresponding move
- [x] Create a type color array and change the color of the button based on the move type
- [x] If the current Pokemon has more energy than the move energy, the excess energy should show as a second layer on the background

![IMG_0443](https://user-images.githubusercontent.com/26877561/103446152-88b84280-4c4a-11eb-8623-155270d3fd63.jpg)
![IMG_0444](https://user-images.githubusercontent.com/26877561/103446153-8950d900-4c4a-11eb-85b9-f6fb7bd9764f.jpg)
![IMG_0445](https://user-images.githubusercontent.com/26877561/103446154-8950d900-4c4a-11eb-8cad-ca06906ab8bd.jpg)

### Notes

- [I recommend using css background gradient to achieve the filling up effect](https://stackoverflow.com/questions/52950627/inline-style-in-react-background-linear-gradient/59546630#59546630)
- The label should become bold when the charge move is available, and the component should scale up (you can achieve a nice animation with css transition)
- Pressing a button should have a "scale down" effect
- Don't worry about type icons, for now use a dummy icon

**Comment by theking465** [comment]
Relevant PR: #14

**Comment by DeveloperKhan** [comment]
Completed on the Game_charge_moves branch
