### ISSUE TITLE
Feat: sort pokemon by prefix

### ISSUE THREAD

**Issue by FlorianKutz** [DeveloperKhan/pogo-web#110]
When I use the searchbar for species in the teambuilder and I type in "a", I expect to see a lot of Pokémon that start with this letter. However, the first result is "Bulbasaur".

Solution: Sort the results so that all Pokémon that have the input as their prefix, are first.

**Comment by ameybhavsar24** [comment]
It is unclear how will results that don't have their prefix as input will be sorted.
I think it would be better to at least sort all results alphabetically.

**Comment by FlorianKutz** [comment]
@ameybhavsar24 I disagree. When I type in "Rai", the first results I want to see are the Raichus and Raikou, not Braixen and Darkrai.

We can have a primary and secondary sort option. The isPrefix would be the primary and the secondary is debatable. Maybe dexnumber, maybe pvpoke-rating, maybe alphabetically.
