### ISSUE TITLE
Refactor: Migrate static files to Firestore/CDN

### ISSUE THREAD

**Issue by DeveloperKhan** [DeveloperKhan/pogo-web#12]
The JSON and png assets from `{backend}/public/mini` and `{backend}/public/models` should be removed from the backend repository and instead stored in Cloud Firestore.

### Requirements

- [x] Move the above assets to Cloud Firestore
- [x] Refactor all references to these assets on both client and server repos

**Comment by ophidianab** [comment]
What impact would doing so have on someone else self-hosting their own instance of the project? Is that a use case you want to preserve?

**Comment by DeveloperKhan** [comment]
> What impact would doing so have on someone else self-hosting their own instance of the project? Is that a use case you want to preserve?

Oh yeh that is a great thing to consider. Since our image data is straight from Pokemon Showdown (unedited), others can just reference that github repository. I'll update the README about it after this issue is closed. For the Pokemon and move data, I will change the issue description so that those are kept within the static express directory. Not only for people that want to make their own instances, but it also lets us have multiple express instances with different game masters opening up the opportunity for custom games/mods.

**Comment by DeveloperKhan** [comment]
Probably good to switch to S3 + Cloudfront in the future, but for now it works great!
