### ISSUE TITLE
Fix: make backend https

### ISSUE THREAD

**Issue by FlorianKutz** [DeveloperKhan/pogo-web#129]
![Screenshot (67)](https://user-images.githubusercontent.com/18531173/115427428-c04ef880-a201-11eb-9933-23a3092e720b.png)
When you visit the current page in production, you get this. As a result, the frontend can't connect to the backend.

**Comment by DeveloperKhan** [comment]
On this! Fixing by switching to projectgrookey.com and permitting SSL

**Comment by FlorianKutz** [comment]
![Screenshot (74)](https://user-images.githubusercontent.com/18531173/115603158-1abe8680-a2e0-11eb-8839-39daa757aef4.png)
Production still doesn't work.
