### ISSUE TITLE
Feat: Pokemon Searching

### ISSUE THREAD

**Issue by DeveloperKhan** [DeveloperKhan/pogo-web#145]
Players should be able to search by Type in the teambuilder. Additionally, the should be able to search by move, generation, and tags (mythical, legendary, etc)

Note: When searching by Frustration or Return, treat it as searching for Shadow and Shadow Eligible.

**Comment by FlorianKutz** [comment]
- [ ] Search by type
- [ ] Search by Move
- [ ] Search by Gen
- [ ] Search by Tag
- [ ] Transform Frustration&Return
