### ISSUE TITLE
Refactor: Switch to Axios

### ISSUE THREAD

**Issue by DeveloperKhan** [DeveloperKhan/pogo-web#18]
Refactor all fetch calls to axios calls. Most of the fetch calls are in the `teambuilder` branch

**Comment by jarthur22** [comment]
Lol I like axios better anyway :)

**Comment by jarthur22** [comment]
I completed the install/use of axios on the teambuilder branch. If I missed any or there are fetch reqs in any other branch feel free to point them out.
