### ISSUE TITLE
Feat: Random Battles

### ISSUE THREAD

**Issue by DeveloperKhan** [DeveloperKhan/pogo-web#186]
Implement a "Random Battle" meta.

### Requirements

- [x] Allow players to select "Random Battle" in the team selector on the homepage
- [ ] When players queue in with "Random Battle," the server should generate a team for them when they connect

### Notes
- You probably need to disable team validation checks to create this feature
- The randomized teams should use PvPoke preferred movesets and use the PvPoke ranking model to create relatively balanced Great League teams

**Comment by FlorianKutz** [comment]
Another note: There is already a getRandomTeam function in the frontend that uses PvPoke rankings and movesets (however the default moveset isn't guaranteed). For the functionality, do this:

- [ ] Move the random Team function to the backend
- [ ] Adapt the function to the new environment. Don't make http calls to yourself.
- [ ] Make a new api endpoint that generates a random team
- [ ] change the frontend's "Random Team"-button so it uses the new http endpoint instead.
- [ ] Add a flag to the rule type called "randomizedTeams" or something like that.
- [ ] When generating a room, give the players randomized teams. Make sure cheaters can't overwrite their teams.
- [ ] Add the logic to the frontend. Honestly I have no idea how it should look on the ui.
