### ISSUE TITLE
Feat: Pokemon Selector

### ISSUE THREAD

**Issue by DeveloperKhan** [DeveloperKhan/pogo-web#2]
Implement a selector for users to visualize their Pokemon team and register individual members.

### Requirements

- [x] Up to 6 tabs for each Pokemon
- [x] Each tab opens a window that looks like:
<img width="203" alt="Screen Shot 2020-12-31 at 3 22 13 PM" src="https://user-images.githubusercontent.com/26877561/103424718-ffd2d580-4b7b-11eb-9b3a-14268e035fe6.png">

### Notes

- The available pokemon for the dropdown can be found from `/data/pokemon` in [the backend repo](https://github.com/DeveloperKhan/pogo-web-backend). **The data folder needs to be moved to the public directory so that the frontend can access it.**
- The `/data/pokemon` JSON includes normal Pokemon and XL Pokemon. We don't care about the difference, so we can ignore XL versions.
- The selector window should assume perfect IVs/level (up to level 51) at Great League CP by default.
- Imagine the dynamic tabs like Pokemon Showdown:
<img width="373" alt="Screen Shot 2020-12-31 at 3 30 24 PM" src="https://user-images.githubusercontent.com/26877561/103424930-28a79a80-4b7d-11eb-89fc-1ca4f4bdf05e.png">

**Comment by jarthur22** [comment]
Pushed the first update for this to new branch `teambuilder`.

- added API routes for Pokemon data
- had to move the initialization of `app` outside of the `startServer()` function in order to get API route middleware to work

**Comment by DeveloperKhan** [comment]
Needs to be a little prettier, but not really a concern
