### ISSUE TITLE
Fix: No quick move damage redirection

### ISSUE THREAD

**Issue by FlorianKutz** [DeveloperKhan/pogo-web#206]
How to reproduce:
1. Play a game. 
2. Player 1 uses a charge move the same moment the opponent uses a quickmove. I recommend Incinerate because it's easier to time.
3. The charge move mustn't ko the pokémon. Player 1 spams "switch" during the 3s time period. Of course the switch timer must be 0 so the switch happens.

Expected: Like in Pokémon Go, the Incinerate damage is inflicted on the pokémon that comes in. 
Actually the previous pokémon is damaged.

**Comment by DeveloperKhan** [comment]
This is kinda difficult because it is inconsistent. If you switch after a charge move, you can catch damage on the switch in (most of the time). However if you switch during normal gameplay, the damage should inflict on the previous Pokemon. We'd have to code for this special case.
