### ISSUE TITLE
Fix: Charge moves in Team builder are always shown in english

### ISSUE THREAD

**Issue by FlorianKutz** [DeveloperKhan/pogo-web#229]
![Screenshot (165)](https://user-images.githubusercontent.com/18531173/121690888-ae355c00-cac6-11eb-914c-5c646e89e02c.png)

**Comment by paoloricciuti** [comment]
I was looking into this. The code to manage multiple languages in the frontend is fairly simple. The tough part in my opinion is update the json in the backend to include the names for every language. I'll try yo check if this process can be automated (it should be automatable) but the process should be repetead on every new pokemon/new moves addition. It might be more mantainable to keep a Map between moves id and displayable name. What do you guys think?

**Comment by DeveloperKhan** [comment]
> I was looking into this. The code to manage multiple languages in the frontend is fairly simple. The tough part in my opinion is update the json in the backend to include the names for every language. I'll try yo check if this process can be automated (it should be automatable) but the process should be repetead on every new pokemon/new moves addition. It might be more mantainable to keep a Map between moves id and displayable name. What do you guys think?

Hey would you be able to contact me through Discord @AdibKhan#5314. We've already setup an automated process for this using Lokalise, but you'd need a .env file from us to get started.

**Comment by paoloricciuti** [comment]
Sure, i've sent you a friend request on discord.
