### ISSUE TITLE
Feat: Loading Indicator

### ISSUE THREAD

**Issue by DeveloperKhan** [DeveloperKhan/pogo-web#23]
Design and implement a loading indicator used for all pages

### Requirements

- [ ] Create a simple loading indicator (either gif or css animation)
- [ ] Replace "Loading..." in `/pages/game`, `/pages/matchup`, `/pages/index` with the indicator

**Comment by jarthur22** [comment]
React bootstrap has a nice loader if we want to use a stripped version of that.

**Comment by DeveloperKhan** [comment]
> React bootstrap has a nice loader if we want to use a stripped version of that.

We can get a separate loading spinner so we don’t have to install the entire library. But yeh I’d be down to just grab some npm loading spinner.
