### ISSUE TITLE
Fix: language reset to english doesn't work

### ISSUE THREAD

**Issue by FlorianKutz** [DeveloperKhan/pogo-web#249]
How to reproduce:
1. Change language to anything other than english
2. Switch back to english

Result: A glitched state. It looks like the language setting didn't change. However, the pokémon names changed

**Comment by paoloricciuti** [comment]
Hey i was looking to contribute to this project. I'm trying to reproduce this bug on the deployed https://projectgrookey.com/ but i'm not able to. Switching back to English just works flawlessly. Could you provide some screenshots?
