### ISSUE TITLE
Feat: Team Verifier

### ISSUE THREAD

**Issue by DeveloperKhan** [DeveloperKhan/pogo-web#3]
Implement a system to insure a Pokemon team is valid for Great, Ultra, or Master League.

### Requirements

- [x] Create a frontend component with a dropdown (options: Great, Ultra, Master) and a submit button
- [x] Create a backend endpoint (not with websockets, just express) that accepts a payload of type `TeamMember[]` and returns EITHER an auth key OR an error

### Notes

- Submit button should be disabled until there are 6 Pokemon selected
- The backend endpoint should loop through each item in the array and cross reference with the `data/pokemon` JSON object to insure each item has valid moves, level, IVs, and CP for the correct league. We should also make sure there is at most 1 level 51 Pokémon.
- The backend endpoint should return a dummy authorization key, eventually this key be required to start a game.

**Comment by tony-xuyf** [comment]
I'll take a look at this. Probably will start with backend logics first.

**Comment by jarthur22** [comment]
Probably best to work with the pokemon api already in `teambuilder` branch for backend

**Comment by jarthur22** [comment]
Self-assigned myself here just so it shows up on my profile, we will likely need to work together between this and the team builder :)

**Comment by tony-xuyf** [comment]
@jarthur22 sorry I just saw this message. Had a PR open for backend changes: https://github.com/DeveloperKhan/pogo-web-backend/pull/1

Feel free to let me know if you have any concerns.

**Comment by jarthur22** [comment]
Oh no it looks great for sure, in the teambuilder branch I added an API with a pokemon route, if you like the look of that and want to expand upon it or add a new route for teams, etc., feel free :)

**Comment by tony-xuyf** [comment]
@jarthur22 Thanks. I tried to expose as API but had some problems. Anyway khan said it's fine to just be in a different handler. I've pushed that change.
