### ISSUE TITLE
Design: Project Grookey Logo

### ISSUE THREAD

**Issue by DeveloperKhan** [DeveloperKhan/pogo-web#34]
Design a Project Grookey Icon, Logo, and E-Sports Team Banner

**Comment by DeveloperKhan** [comment]
![GrookeyLogo-01](https://user-images.githubusercontent.com/26877561/105228934-35426180-5b31-11eb-96b8-7268cddc5d8d.png)
This seems to be the crowd favorite icon

**Comment by theking465** [comment]
It still needs some kind of 👀.

**Comment by DeveloperKhan** [comment]
Will close this issue once the Fiverr guy finishes up today. We'll use @theking465's logo with the eyes.
