### ISSUE TITLE
Feat: Energy Gain

### ISSUE THREAD

**Issue by DeveloperKhan** [DeveloperKhan/pogo-web#4]
Implement energy gain from fast attacks

### Requirements

- [x] Fast moves should appropriately attribute energy within the `evaluatePayload` function of `{backend}/handlers/onTurn.ts`
- [x] The backend should pass new energy values through the `update` array of the onTurn payload
- [x] The frontend should recognize energy updates and update charge meters (it only needs to know if `update[0]` has an `energy` parameter

### Notes

- The `update` array reverses when sending its message to each client, so the frontend can assume `update[0]` refers to the player and not the opponent

**Comment by debopamsengupta** [comment]
I'll take a look at this :)

**Comment by DeveloperKhan** [comment]
Sorry, forgot to close!
