### ISSUE TITLE
Fix: Double Speed Game Timer

### ISSUE THREAD

**Issue by DeveloperKhan** [DeveloperKhan/pogo-web#40]
Some games go at double the speed of a regular game. Investigate and fix. This is likely due to the game timer being wrongfully initiated twice.

**Comment by theking465** [comment]
A new timer gets instantiated every time a new game starts on the same backend instance while the old one is also still present.

**Comment by DeveloperKhan** [comment]
> A new timer gets instantiated every time a new game starts on the same backend instance while the old one is also still present.

Kk seems like we need to have some logic that starts the game only if there is no old instance. I’ll look into it!
