### ISSUE TITLE
Fix: Screen "shaking" on click

### ISSUE THREAD

**Issue by theking465** [DeveloperKhan/pogo-web#43]
On the matchup page when clicking on certain parts of the screen it performs a small "shake" animation. This only happens if the team isn't submitted yet.

**Comment by DeveloperKhan** [comment]
Is this it?
https://user-images.githubusercontent.com/26877561/106332353-a3cf9f80-6254-11eb-9d2d-3928b8a1a2ed.mov

**Comment by theking465** [comment]
That's part of the problem yep, the start button registers click outside of its intended box. And for some reason that click has a shake animation attached.

**Comment by DeveloperKhan** [comment]
This has magically gone away. Haven't tested on all browsers, but this issue is now irrelevant after the homepage redesign
