### ISSUE TITLE
Fix: Trio Selector

### ISSUE THREAD

**Issue by DeveloperKhan** [DeveloperKhan/pogo-web#5]
The logic and state management for `{frontend}/src/components/select` is incorrect. From start, if you press the same Pokemon multiple times, the labels will be: "1" -> "" -> "2" -> "" -> "3" -> "" -> "3" -> ""

Whereas, expected behavior should be: "1" -> "" -> "1" -> ""

There are cascading issues with ordering after this happens. Please investigate and correct the logic so that there can never be a number without its left adjacent number and so that there can never be two of the same number.

**Comment by theking465** [comment]
Issue solved in #13
