### ISSUE TITLE
Feat: team validation

### ISSUE THREAD

**Issue by theking465** [DeveloperKhan/pogo-web#56]
When creating a team for a specific league it should not be saved as long as the team has a member with a cp value higher as the league it's in. 

This can be done by calling the validation endpoint and disabling the save button whilst it returns false. 
There should be a small message to make this clear to the user.

**Comment by theking465** [comment]
As an addition, the team validator should also check if a team is empty to prevent a player from starting a game with an empty team

**Comment by DeveloperKhan** [comment]
just pushed this feature. i forgot about the empty team clause, but the game shouldn't be able to let you enter with a team less than 3 anyways. i'll make that a seperate issue
