### ISSUE TITLE
Fix: Last Pokemon Faint Timer

### ISSUE THREAD

**Issue by DeveloperKhan** [DeveloperKhan/pogo-web#59]
When KO'ing the 2nd to last Pokemon (e.i. one Pokemon left remaining), the switch timer should be around 3 seconds instead of the full length of time.

**Comment by FlorianKutz** [comment]
Fixed in https://github.com/DeveloperKhan/pogo-web-backend/commit/a480e950092b380329b146ad155987b96ee7fb8e
