### ISSUE TITLE
Feat: Discord Bot

### ISSUE THREAD

**Issue by DeveloperKhan** [DeveloperKhan/pogo-web#6]
### Requirements
- A welcome message for new members
- A GO Stadium-style message where developers can specify whether they are backend or frontend
- A Github channel that makes messages for new PRs and new issues

### Notes
- For now we can manually give people the developer/designer role
- The react-for-role message should be on a developer -> `#roles` channel

**Comment by theking465** [comment]
Discord bot live at: https://github.com/theking465/thwackey-bot

**Comment by DeveloperKhan** [comment]
Hooray, first issue to close!
